In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('../data/cleaned_dataset.csv')
df.head()

,date,commodity_group,commodity,unit,price_prevailing
0,2025-03-01,Basic Goods,Brown Sugar,kg,74.65
1,2025-03-01,Basic Goods,Chicken Egg (Medium White),piece,7.97
2,2025-03-01,Basic Goods,Cooking Oil (Coconut),bottle (1L),128.61
3,2025-03-01,Basic Goods,Cooking Oil (Palm),bottle (1L),100.95
4,2025-03-01,Basic Goods,Refined Sugar,kg,82.93

In [ ]:
# Shape of the dataset
print(f"Shape of the dataset: {df.shape}")

Shape of the dataset: (66291, 5)

In [ ]:
len(df['date'].unique())

451

In [ ]:
df.groupby('commodity_group')['price_prevailing'].describe().sort_values(by='mean', ascending=False)

,count,mean,std,min,25%,50%,75%,max
commodity_group,,,,,,,,
Meat & Poultry,7343.0,327.669435,99.465787,100.00,228.7650,325.170,406.1950,672.00
Fish,1198.0,282.844432,71.101953,106.67,246.2950,271.010,332.5175,613.64
Other,36412.0,240.417311,140.151757,6.11,142.4275,221.505,344.0000,757.46
Spices,3087.0,183.628005,108.065296,75.00,113.0800,147.660,187.3500,753.08
Highland Vegetables,6253.0,176.653953,96.255908,42.23,101.5600,154.900,234.2000,704.00
Lowland Vegetables,836.0,129.282907,66.888462,43.50,98.2200,115.470,143.1525,412.27
Fruits,3480.0,127.542782,77.660678,47.62,75.8475,99.780,169.7075,488.18
Other Basic Goods,1884.0,86.588790,95.961382,20.00,39.1400,74.590,82.1100,661.25
Rice & Cereals,5798.0,69.857829,39.454862,8.36,47.5000,58.220,77.7800,750.00

In [5]:
# count the number of dates in the dataset
df['date'].nunique()

597