In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('../data/raw_da_amas_prices.csv')
df = df[['date', 'commodity_group', 'commodity', 'variety','price_prevailing']]
df.head()

,date,commodity_group,commodity,variety,price_prevailing
0,2025-03-01,Fish,Alumahan,Medium (4-6pcs/kg),358.33
1,2025-03-01,Fish,Bangus,Large,233.83
2,2025-03-01,Fish,Bangus,Medium (3-4pcs/kg),206.83
3,2025-03-01,Fish,Galunggong (Imported),"Male, Medium (12- 14pcs/kg)",300.00
4,2025-03-01,Fish,Galunggong (Local),"Male, Medium (12- 14pcs/kg)",311.67

In [4]:
# Shape of the dataset
print(f"Shape of the dataset: {df.shape}")

Shape of the dataset: (66291, 5)

In [5]:
len(df['date'].unique())

451

In [6]:
df.groupby('commodity_group')['price_prevailing'].describe().sort_values(by='mean', ascending=False)

,count,mean,std,min,25%,50%,75%,max
commodity_group,,,,,,,,
Meat & Poultry,7343.0,327.669435,99.465787,100.00,228.7650,325.170,406.1950,672.00
Fish,1198.0,282.844432,71.101953,106.67,246.2950,271.010,332.5175,613.64
Other,36412.0,240.417311,140.151757,6.11,142.4275,221.505,344.0000,757.46
Spices,3087.0,183.628005,108.065296,75.00,113.0800,147.660,187.3500,753.08
Highland Vegetables,6253.0,176.653953,96.255908,42.23,101.5600,154.900,234.2000,704.00
Lowland Vegetables,836.0,129.282907,66.888462,43.50,98.2200,115.470,143.1525,412.27
Fruits,3480.0,127.542782,77.660678,47.62,75.8475,99.780,169.7075,488.18
Other Basic Goods,1884.0,86.588790,95.961382,20.00,39.1400,74.590,82.1100,661.25
Rice & Cereals,5798.0,69.857829,39.454862,8.36,47.5000,58.220,77.7800,750.00

In [7]:
oct_20 = df[
  (df['date'] == '2026-10-20') &
  (df['commodity_group'] == 'Highland Vegetables')
]

oct_20

,date,commodity_group,commodity,variety,price_prevailing
66158,2026-10-20,Highland Vegetables,"Bell Pepper (Green), Local",Medium (151-250gm/pc),315.75
66159,2026-10-20,Highland Vegetables,"Bell Pepper (Red), Local",Medium (151-250gm/pc),292.57
66160,2026-10-20,Highland Vegetables,"Broccoli, Imported",Standard,287.30
66161,2026-10-20,Highland Vegetables,Cabbage (Rare Ball),510 gm - 1 kg/head,155.41
66162,2026-10-20,Highland Vegetables,Cabbage (Scorpio),750 gm - 1 kg/head,152.50
66163,2026-10-20,Highland Vegetables,Cabbage (Wonder Ball),510 gm - 1 kg/head,152.12
66164,2026-10-20,Highland Vegetables,"Carrots, Imported",Standard,119.47
66165,2026-10-20,Highland Vegetables,"Carrots, Local",8-10 pcs/kg,128.69
66166,2026-10-20,Highland Vegetables,"Cauliflower, Local",Medium (8-10 cm diameter/bunch hd),325.60
66167,2026-10-20,Highland Vegetables,Celery,Medium (501-800 g),319.40
66168,2026-10-20,Highland Vegetables,Chayote,Medium (301-400 g),60.49
66169,2026-10-20,Highland Vegetables,"Habichuelas/Baguio Beans, Local",Standard,133.66
66170,2026-10-20,Highland Vegetables,Lettuce (Green Ice),Standard,208.21
66171,2026-10-20,Highland Vegetables,Lettuce (Iceberg),Medium (301-450 cm diameter/bunch hd),302.89
66172,2026-10-20,Highland Vegetables,Lettuce (Romaine),Standard,198.33
66173,2026-10-20,Highland Vegetables,Pechay Baguio,Standard,121.88